language: node_js
node_js:
  - '4'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9992cd0d36a6ba9bb40b
    on_success: change
    on_failure: always
    on_start: never
before_install:
  - sudo apt-get install -y rpm
  - gem install fpm
install:
  - make test
script:
  - make build
  - make packages
before_deploy:
  - export RELEASE_PKG_TAR=$(ls build/moira-web*.tar.gz)
  - export RELEASE_PKG_RPM=$(ls build/moira-web*.rpm)
  - export RELEASE_PKG_DEB=$(ls build/moira-web*.deb)
deploy:
  provider: releases
  api_key:
    secure: Xoo4SzDifjrsg826p+QMrCeZyPbELgSbmrBkF6TyezP2fli+riPsn+zassWMmN3K6lvNXQHCanjKFJ/K98SSbvT8JacpT4CPh45FEAZwADnENwIwUmjmUouT2rfnso0XPc3S6MIvBFlfidjvGJBjeOp6/6tRmA0yghk9eQIglo4OUwn21F4JVEinGuC6P/28xFX7gpEcjoII8SwJHAGQZaa9UJK2gDbRcLuziQ8G0vDjWtiPuumxou/nq6KWtUca6cGkbuJASeWNKqbh56BryrNBpBWzzQVxHkg1Ri7tyZ3iWpn3VFaTd4Us6DlEA4rKRN+QqiZbqqApxEk8ldQ5JOGGEPZOIHXFeHytJlezc+R6IeQpsZ4LO7C2dBhRbapA7U6kF+Z414Ay+LJn0g3ARJw8iMochIQkYKGpnUVqxIZ0u40ryK5Fg2Xqd5MiAWio2YTTCpV5Hu5DAgDRyeV7vTTQ/ZnkzieSQ/aolfjhnpGNOgFTB4c50gCLXECCary2LtTZEZSMpIU0P4SCerOyMmtPTLfpKinf9DmVHl2lmvlDjaZAUf4p3RPto8RNdXM//aLgfGZq4bBU4OOOWUuSUfOi7WQSYN0fXs0AKT5OhSdEjUDXlp4Tl8hC2W8IpdpPDtdg3HgUMrkpnihGto71uJlAIQT+9e4ABT5Tg+rWNFU=
  file:
    - "${RELEASE_PKG_TAR}"
    - "${RELEASE_PKG_RPM}"
    - "${RELEASE_PKG_DEB}"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = 4
    branch: master
